# -*- coding: utf-8 -*-
"""ISIMIP_NetCDF_File_Downloader.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AvFNXu_FxwVSTB0WGslWfg_FtKZoj9vT
"""



# ISIMIP NetCDF File Downloader for Google Colab
# ==============================================
# This script automates downloading NetCDF files from ISIMIP data portal.

# SECTION 1 - Import libraries

import os
import time
import logging
import requests
import pandas as pd
from pathlib import Path
from typing import List, Dict, Optional, Tuple
from urllib.parse import urljoin, urlparse
from datetime import datetime
from concurrent.futures import ThreadPoolExecutor, as_completed

# Import BeautifulSoup for web scraping
from bs4 import BeautifulSoup

# Import tqdm for progress bars
from tqdm import tqdm

# For Google Colab Drive mounting
from google.colab import drive



# ============================================================================
# SECTION 2 - CONFIGURATION SECTION - Modify these settings as needed
# ============================================================================

# Default configuration
CONFIG = {
    'max_retries': 3,              # Number of retry attempts for failed downloads
    'timeout': 30,                  # Request timeout in seconds
    'chunk_size': 8192,             # Download chunk size in bytes
    'max_workers': 3,               # Number of parallel downloads
    'delay_between_requests': 1,    # Delay between requests to avoid overwhelming server
    'gdrive_folder': 'ISIMIP_Data', # Folder name in Google Drive
    'log_file': 'isimip_download.log',
    'report_file': 'download_report.csv'
}

# Headers to mimic a browser request
HEADERS = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
}

# ============================================================================
# SECTION 3 - LOGGING SETUP
# ============================================================================

def setup_logging(log_file: str) -> logging.Logger:
    """
    Set up logging configuration.

    Args:
        log_file: Path to log file

    Returns:
        Logger instance
    """
    # Create logger
    logger = logging.getLogger('ISIMIP_Downloader')
    logger.setLevel(logging.INFO)

    # Create formatters
    file_formatter = logging.Formatter(
        '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    )
    console_formatter = logging.Formatter('%(levelname)s: %(message)s')

    # File handler
    fh = logging.FileHandler(log_file)
    fh.setLevel(logging.INFO)
    fh.setFormatter(file_formatter)

    # Console handler
    ch = logging.StreamHandler()
    ch.setLevel(logging.INFO)
    ch.setFormatter(console_formatter)

    # Add handlers to logger
    logger.addHandler(fh)
    logger.addHandler(ch)

    return logger

# ============================================================================
# SECTION 4 - GOOGLE DRIVE SETUP
# ============================================================================

def setup_google_drive(folder_name: str) -> Path:
    """
    Mount Google Drive and create download folder.

    Args:
        folder_name: Name of folder to create in Google Drive

    Returns:
        Path to the download folder
    """
    print("🔗 Mounting Google Drive...")
    drive.mount('/content/drive')

    # Create download folder
    download_path = Path(f'/content/drive/MyDrive/{folder_name}')
    download_path.mkdir(exist_ok=True)

    print(f"✅ Download folder created: {download_path}")
    return download_path

# ============================================================================
# SECTION 5 - FILE OPERATIONS
# ============================================================================

def load_urls_from_excel(file_path: str) -> pd.DataFrame:
    """
    Load URLs and metadata from Excel file.

    Args:
        file_path: Path to Excel file

    Returns:
        DataFrame with URL data
    """
    logger = logging.getLogger('ISIMIP_Downloader')

    try:
        logger.info(f"Loading URLs from {file_path}")
        df = pd.read_excel(file_path)

        # Validate required columns
        required_cols = ['Placeholder_Download_Link', 'Dataset']
        missing_cols = [col for col in required_cols if col not in df.columns]

        if missing_cols:
            raise ValueError(f"Missing required columns: {missing_cols}")

        logger.info(f"Loaded {len(df)} URLs from Excel file")
        return df

    except Exception as e:
        logger.error(f"Error loading Excel file: {e}")
        raise

def get_filename_from_url(url: str, dataset_name: str) -> str:
    """
    Generate filename from URL and dataset info.

    Args:
        url: Download URL
        dataset_name: Dataset name from Excel

    Returns:
        Filename for saving
    """
    # Extract UUID from URL
    parsed = urlparse(url)
    uuid = parsed.path.split('/')[-2] if parsed.path.endswith('/') else parsed.path.split('/')[-1]

    # Create filename: dataset_uuid.nc
    filename = f"{dataset_name}_{uuid}.nc"

    # Clean filename (remove any invalid characters)
    invalid_chars = '<>:"|?*'
    for char in invalid_chars:
        filename = filename.replace(char, '_')

    return filename

# ============================================================================
# SECTION 6 - WEB SCRAPING
# ============================================================================

def find_nc_download_link(page_url: str, session: requests.Session) -> Optional[str]:
    """
    Scrape ISIMIP page to find the .nc file download link.

    Args:
        page_url: URL of the ISIMIP page
        session: Requests session object

    Returns:
        Direct download URL for .nc file, or None if not found
    """
    logger = logging.getLogger('ISIMIP_Downloader')

    try:
        # Add delay to be respectful to the server
        time.sleep(CONFIG['delay_between_requests'])

        # Get the page
        response = session.get(page_url, timeout=CONFIG['timeout'])
        response.raise_for_status()

        # Parse HTML
        soup = BeautifulSoup(response.text, 'html.parser')

        # Strategy 1: Look for direct download links
        # Search for links containing .nc extension
        nc_links = []
        for link in soup.find_all('a', href=True):
            href = link['href']
            if '.nc' in href:
                nc_links.append(href)

        # Strategy 2: Look for download buttons or specific classes
        # (This may need adjustment based on actual ISIMIP HTML structure)
        download_buttons = soup.find_all('a', class_=['download', 'btn-download', 'download-link'])
        for btn in download_buttons:
            if 'href' in btn.attrs:
                nc_links.append(btn['href'])

        # Strategy 3: Look for links with specific patterns
        # ISIMIP might use specific URL patterns for downloads
        for link in soup.find_all('a', href=True):
            href = link['href']
            if any(pattern in href for pattern in ['download', 'files', '.nc']):
                nc_links.append(href)

        # Remove duplicates and filter for .nc files
        nc_links = list(set(nc_links))
        nc_links = [link for link in nc_links if link.endswith('.nc')]

        if nc_links:
            # Convert relative URLs to absolute
            download_url = urljoin(page_url, nc_links[0])
            logger.info(f"Found .nc download link: {download_url}")
            return download_url
        else:
            logger.warning(f"No .nc download link found on page: {page_url}")
            return None

    except requests.RequestException as e:
        logger.error(f"Error accessing page {page_url}: {e}")
        return None
    except Exception as e:
        logger.error(f"Unexpected error while scraping {page_url}: {e}")
        return None

# ============================================================================
# SECTION 7 - DOWNLOAD FUNCTIONS
# ============================================================================

def download_file(url: str, filepath: Path, session: requests.Session) -> bool:
    """
    Download a file with progress bar and resume capability.

    Args:
        url: Download URL
        filepath: Path where to save the file
        session: Requests session object

    Returns:
        True if successful, False otherwise
    """
    logger = logging.getLogger('ISIMIP_Downloader')

    # Check if file already exists
    if filepath.exists():
        existing_size = filepath.stat().st_size
        headers = {'Range': f'bytes={existing_size}-'}
        mode = 'ab'
        logger.info(f"Resuming download from byte {existing_size}")
    else:
        headers = {}
        mode = 'wb'
        existing_size = 0

    try:
        # Add delay
        time.sleep(CONFIG['delay_between_requests'])

        # Make request
        response = session.get(url, headers=headers, stream=True, timeout=CONFIG['timeout'])
        response.raise_for_status()

        # Get total file size
        total_size = int(response.headers.get('content-length', 0)) + existing_size

        # Download with progress bar
        with open(filepath, mode) as f:
            with tqdm(total=total_size, initial=existing_size,
                     unit='B', unit_scale=True, desc=filepath.name) as pbar:
                for chunk in response.iter_content(chunk_size=CONFIG['chunk_size']):
                    if chunk:
                        f.write(chunk)
                        pbar.update(len(chunk))

        logger.info(f"Successfully downloaded: {filepath.name}")
        return True

    except Exception as e:
        logger.error(f"Error downloading {url}: {e}")
        return False

def download_with_retry(url: str, filepath: Path, session: requests.Session) -> bool:
    """
    Download file with retry logic.

    Args:
        url: Download URL
        filepath: Path where to save the file
        session: Requests session object

    Returns:
        True if successful, False otherwise
    """
    logger = logging.getLogger('ISIMIP_Downloader')

    for attempt in range(CONFIG['max_retries']):
        if attempt > 0:
            logger.info(f"Retry attempt {attempt} for {filepath.name}")
            time.sleep(5 * attempt)  # Exponential backoff

        if download_file(url, filepath, session):
            return True

    logger.error(f"Failed to download {filepath.name} after {CONFIG['max_retries']} attempts")
    return False

# ============================================================================
# SECTION 8 - MAIN PROCESSING
# ============================================================================

def process_single_dataset(row: pd.Series, download_path: Path, session: requests.Session) -> Dict:
    """
    Process a single dataset: scrape and download.

    Args:
        row: DataFrame row with dataset info
        download_path: Path to download folder
        session: Requests session object

    Returns:
        Dictionary with processing results
    """
    logger = logging.getLogger('ISIMIP_Downloader')

    result = {
        'dataset': row['Dataset'],
        'page_url': row['Placeholder_Download_Link'],
        'status': 'failed',
        'download_url': None,
        'filepath': None,
        'error': None
    }

    try:
        # Step 1: Find the .nc download link
        logger.info(f"Processing: {row['Dataset']}")
        download_url = find_nc_download_link(row['Placeholder_Download_Link'], session)

        if not download_url:
            result['error'] = 'No .nc download link found'
            return result

        result['download_url'] = download_url

        # Step 2: Generate filename and download
        filename = get_filename_from_url(download_url, row['Dataset'])
        filepath = download_path / filename
        result['filepath'] = str(filepath)

        # Step 3: Download the file
        if download_with_retry(download_url, filepath, session):
            result['status'] = 'success'
        else:
            result['error'] = 'Download failed'

    except Exception as e:
        logger.error(f"Error processing {row['Dataset']}: {e}")
        result['error'] = str(e)

    return result

def process_all_datasets(df: pd.DataFrame, download_path: Path, parallel: bool = False) -> List[Dict]:
    """
    Process all datasets from the DataFrame.

    Args:
        df: DataFrame with dataset information
        download_path: Path to download folder
        parallel: Whether to use parallel downloads

    Returns:
        List of processing results
    """
    logger = logging.getLogger('ISIMIP_Downloader')
    results = []

    # Create session for connection pooling
    session = requests.Session()
    session.headers.update(HEADERS)

    if parallel:
        logger.info(f"Starting parallel download with {CONFIG['max_workers']} workers")

        with ThreadPoolExecutor(max_workers=CONFIG['max_workers']) as executor:
            # Submit all tasks
            future_to_row = {
                executor.submit(process_single_dataset, row, download_path, session): idx
                for idx, row in df.iterrows()
            }

            # Process completed tasks with progress bar
            with tqdm(total=len(df), desc="Overall Progress") as pbar:
                for future in as_completed(future_to_row):
                    result = future.result()
                    results.append(result)
                    pbar.update(1)
    else:
        logger.info("Starting sequential download")

        # Process sequentially with progress bar
        for idx, row in tqdm(df.iterrows(), total=len(df), desc="Overall Progress"):
            result = process_single_dataset(row, download_path, session)
            results.append(result)

    session.close()
    return results

# ============================================================================
# SECTION 9 - REPORTING
# ============================================================================

def generate_report(results: List[Dict], report_path: str):
    """
    Generate a CSV report of download results.

    Args:
        results: List of processing results
        report_path: Path to save the report
    """
    logger = logging.getLogger('ISIMIP_Downloader')

    # Convert to DataFrame
    report_df = pd.DataFrame(results)

    # Save to CSV
    report_df.to_csv(report_path, index=False)
    logger.info(f"Report saved to: {report_path}")

    # Print summary
    total = len(results)
    success = len([r for r in results if r['status'] == 'success'])
    failed = total - success

    print("\n" + "="*50)
    print("DOWNLOAD SUMMARY")
    print("="*50)
    print(f"Total datasets: {total}")
    print(f"✅ Successful: {success}")
    print(f"❌ Failed: {failed}")
    print(f"Success rate: {success/total*100:.1f}%")
    print("="*50)

    # Show failed downloads
    if failed > 0:
        print("\nFailed downloads:")
        for r in results:
            if r['status'] != 'success':
                print(f"- {r['dataset']}: {r['error']}")

# ============================================================================
# SECTION 10 - MAIN FUNCTION
# ============================================================================

def test_single_download(df: pd.DataFrame, download_path: Path) -> bool:
    """
    Test download functionality with a single file.

    Args:
        df: DataFrame with dataset information
        download_path: Path to download folder

    Returns:
        True if test successful, False otherwise
    """
    logger = logging.getLogger('ISIMIP_Downloader')
    print("\n🧪 Running test download...")

    # Create session
    session = requests.Session()
    session.headers.update(HEADERS)

    # Test with first dataset
    test_row = df.iloc[0]
    print(f"Testing with dataset: {test_row['Dataset']}")
    print(f"Page URL: {test_row['Placeholder_Download_Link']}")

    # Test scraping
    print("\n1️⃣ Testing web scraping...")
    download_url = find_nc_download_link(test_row['Placeholder_Download_Link'], session)

    if not download_url:
        print("❌ Failed to find .nc download link")
        print("The web scraping function may need adjustment for ISIMIP's HTML structure")
        return False

    print(f"✅ Found download URL: {download_url}")

    # Test download (just get headers, don't download full file)
    print("\n2️⃣ Testing download connection...")
    try:
        response = session.head(download_url, timeout=CONFIG['timeout'])
        response.raise_for_status()

        # Get file size
        file_size = int(response.headers.get('content-length', 0))
        file_size_mb = file_size / (1024 * 1024)

        print(f"✅ Download URL is accessible")
        print(f"📦 File size: {file_size_mb:.1f} MB")

        # Optional: Download first 1MB as test
        print("\n3️⃣ Downloading first 1MB as test...")
        test_filename = f"TEST_{test_row['Dataset']}.nc.partial"
        test_filepath = download_path / test_filename

        response = session.get(download_url, stream=True, timeout=CONFIG['timeout'])
        response.raise_for_status()

        downloaded = 0
        with open(test_filepath, 'wb') as f:
            for chunk in response.iter_content(chunk_size=CONFIG['chunk_size']):
                if chunk:
                    f.write(chunk)
                    downloaded += len(chunk)
                    if downloaded >= 1024 * 1024:  # 1MB
                        break

        print(f"✅ Successfully downloaded test file: {test_filename}")
        print(f"📍 Location: {test_filepath}")

        session.close()
        return True

    except Exception as e:
        print(f"❌ Test failed: {e}")
        session.close()
        return False

def estimate_download_size(df: pd.DataFrame) -> None:
    """
    Estimate total download size based on a sample.

    Args:
        df: DataFrame with dataset information
    """
    print("\n📊 Estimating total download size...")
    print("(This is a rough estimate based on checking a few files)")

    session = requests.Session()
    session.headers.update(HEADERS)

    # Sample 5 random datasets
    sample_size = min(5, len(df))
    sample_df = df.sample(n=sample_size)

    total_size = 0
    successful_checks = 0

    for _, row in sample_df.iterrows():
        try:
            # Find download link
            download_url = find_nc_download_link(row['Placeholder_Download_Link'], session)
            if download_url:
                # Get file size without downloading
                response = session.head(download_url, timeout=10)
                if response.status_code == 200:
                    file_size = int(response.headers.get('content-length', 0))
                    total_size += file_size
                    successful_checks += 1
                    print(f"  • {row['Dataset']}: {file_size/(1024**2):.1f} MB")
            time.sleep(1)  # Be nice to the server
        except:
            pass

    session.close()

    if successful_checks > 0:
        avg_size = total_size / successful_checks
        estimated_total = (avg_size * len(df)) / (1024**3)  # Convert to GB
        print(f"\n📈 Estimated total download size: ~{estimated_total:.1f} GB")
        print(f"   (Based on {successful_checks} samples, ~{avg_size/(1024**2):.1f} MB per file)")
    else:
        print("❌ Could not estimate download size")

def main():
    """
    Main function to orchestrate the entire download process.
    """
    print("🚀 ISIMIP NetCDF Downloader")
    print("="*50)

    # Setup logging
    logger = setup_logging(CONFIG['log_file'])
    logger.info("Starting ISIMIP download process")

    try:
        # Step 1: Setup Google Drive
        download_path = setup_google_drive(CONFIG['gdrive_folder'])

        # Step 2: Load URLs from Excel
        excel_file = 'isimip_download_list.xlsx'
        print(f"\n📊 Loading URLs from {excel_file}")
        df = load_urls_from_excel(excel_file)
        print(f"Found {len(df)} datasets to download")

        # Step 3: Run test download
        if not test_single_download(df, download_path):
            print("\n⚠️ Test download failed!")
            print("Please check the web scraping function or network connection")

            # Ask if user wants to continue anyway
            continue_anyway = input("\nContinue anyway? (yes/no): ").strip().lower()
            if continue_anyway != 'yes':
                print("Exiting...")
                return

        # Step 4: Estimate download size
        estimate_download_size(df)

        # Step 5: Confirm before proceeding
        print("\n" + "="*50)
        print("⚠️  DOWNLOAD CONFIRMATION")
        print("="*50)
        print(f"You're about to download {len(df)} NetCDF files")
        print("This could take several hours and use significant bandwidth")
        print("\nOptions:")
        print("1. Download ALL files")
        print("2. Download first 10 files only")
        print("3. Download first N files (you choose)")
        print("4. Exit")

        choice = input("\nEnter your choice (1-4): ").strip()

        if choice == '1':
            df_to_process = df
        elif choice == '2':
            df_to_process = df.head(10)
            print(f"\n📝 Processing first 10 files only")
        elif choice == '3':
            n = int(input("How many files to download? "))
            df_to_process = df.head(n)
            print(f"\n📝 Processing first {n} files")
        else:
            print("Exiting...")
            return

        # Step 6: Ask about download mode
        print("\n🤔 Choose download mode:")
        print("1. Sequential (slower but more stable)")
        print("2. Parallel (faster but uses more resources)")

        mode_choice = input("Enter your choice (1 or 2): ").strip()
        parallel = mode_choice == '2'

        # Step 7: Process datasets
        print(f"\n⬇️ Starting {'parallel' if parallel else 'sequential'} download...")
        start_time = time.time()

        results = process_all_datasets(df_to_process, download_path, parallel=parallel)

        # Step 8: Generate report
        report_path = download_path / CONFIG['report_file']
        generate_report(results, report_path)

        # Calculate elapsed time
        elapsed_time = time.time() - start_time
        print(f"\n⏱️ Total time: {elapsed_time/60:.1f} minutes")

        logger.info("Download process completed")

    except KeyboardInterrupt:
        logger.warning("Process interrupted by user")
        print("\n⚠️ Download interrupted by user")
    except Exception as e:
        logger.error(f"Fatal error: {e}")
        print(f"\n❌ Error: {e}")
        raise

# ============================================================================
# SECTION 11 - ENTRY POINT
# ============================================================================

if __name__ == "__main__":
    main()

from google.colab import drive
drive.mount('/content/drive')

import os
folder = '/content/drive/MyDrive/ISIMIP_Data'
nc_files = [f for f in os.listdir(folder) if f.endswith('.nc')]
print(f"Total .nc files in Drive: {len(nc_files)}")
print(f"Total size: {sum(os.path.getsize(os.path.join(folder, f)) for f in nc_files) / (1024**3):.1f} GB")