# -*- coding: utf-8 -*-
"""ISIMIP ERA5 Downloader.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G1W3iDn4JZ997mv0pGQDzifCEIjM4O9V
"""

# -*- coding: utf-8 -*-
"""
ISIMIP 20CRv3-ERA5 Europe Downloader - Version 3
=================================================
Downloads ISIMIP3a reanalysis data (20CRv3-ERA5) for Europe, 2018-2021.

Changes from v2:
- Fixed water file paths: 1901soc instead of histsoc
- Fixed water variables: soilmoist, dis instead of qtot, mrso
- Improved skip logic for already downloaded files
- Better file size verification

Target events:
- Vaia windstorm: October 2018 (Alps)
- Western Europe floods: July 2021 (Germany/Belgium)
- Greece fire-weather: August 2021

Consistency: Both climate inputs and H08 outputs use 20CRv3-ERA5 forcing.
"""

import os
import sys
import time
import logging
import requests
from pathlib import Path
from typing import List, Dict, Optional, Tuple
from datetime import datetime

# =============================================================================
# INSTALL DEPENDENCIES
# =============================================================================

def install_packages():
    """Install required packages."""
    packages = ['tqdm', 'isimip-client']
    for pkg in packages:
        try:
            __import__(pkg.replace('-', '_'))
        except ImportError:
            print(f"Installing {pkg}...")
            os.system(f"pip install {pkg} -q")

install_packages()

from tqdm import tqdm

# Try isimip-client (optional, for file discovery)
try:
    from isimip_client.client import ISIMIPClient
    HAS_ISIMIP_CLIENT = True
except ImportError:
    HAS_ISIMIP_CLIENT = False
    print("Note: isimip-client not available, using manual file paths")

# =============================================================================
# CONFIGURATION
# =============================================================================

class Config:
    """Configuration settings."""

    # === MODIFY THESE SETTINGS ===
    USE_COLAB = True
    GDRIVE_FOLDER = "ISIMIP_Data/20crv3-era5_europe"
    LOCAL_DOWNLOAD_PATH = "./isimip_data"

    # Europe bounding box (for local subsetting later)
    EUROPE_BBOX = (35.0, 72.0, -15.0, 45.0)  # lat_min, lat_max, lon_min, lon_max

    # Time period
    START_YEAR = 2018
    END_YEAR = 2021

    # Climate variables (20CRv3-ERA5 input data)
    CLIMATE_VARIABLES = ["pr", "tasmax", "hurs", "sfcwind", "ps"]

    # Water variables - CORRECTED based on actual ISIMIP data availability
    # H08 with 20crv3-era5 provides: soilmoist, dis (not qtot, mrso)
    WATER_VARIABLES = ["soilmoist", "dis"]
    WATER_MODEL = "h08"
    WATER_SOCIAL_SCENARIO = "1901soc"  # CORRECTED: was histsoc

    # Download settings
    MAX_RETRIES = 3
    TIMEOUT = 120
    CHUNK_SIZE = 32768
    DELAY_BETWEEN_REQUESTS = 0.5

    # Skip settings
    SKIP_EXISTING = True  # Skip files that already exist and are complete
    SIZE_TOLERANCE = 0.01  # 1% tolerance for file size comparison


CONFIG = Config()

# =============================================================================
# LOGGING
# =============================================================================

def setup_logging(log_dir: Path) -> logging.Logger:
    """Set up logging."""
    log_dir.mkdir(parents=True, exist_ok=True)
    log_file = log_dir / f"download_{datetime.now().strftime('%Y%m%d_%H%M%S')}.log"

    logger = logging.getLogger('ISIMIP')
    logger.setLevel(logging.DEBUG)

    fh = logging.FileHandler(log_file)
    fh.setLevel(logging.DEBUG)

    ch = logging.StreamHandler()
    ch.setLevel(logging.INFO)

    fmt = logging.Formatter('%(asctime)s - %(levelname)s - %(message)s')
    fh.setFormatter(fmt)
    ch.setFormatter(fmt)

    logger.addHandler(fh)
    logger.addHandler(ch)

    return logger


# =============================================================================
# PATH SETUP
# =============================================================================

def setup_download_path() -> Path:
    """Set up download directory."""
    if CONFIG.USE_COLAB:
        try:
            from google.colab import drive
            drive.mount('/content/drive')
            path = Path(f"/content/drive/MyDrive/{CONFIG.GDRIVE_FOLDER}")
        except:
            print("Not in Colab or Drive mount failed. Using local path.")
            path = Path(CONFIG.LOCAL_DOWNLOAD_PATH)
    else:
        path = Path(CONFIG.LOCAL_DOWNLOAD_PATH)

    path.mkdir(parents=True, exist_ok=True)
    return path


# =============================================================================
# FILE DISCOVERY
# =============================================================================

def get_climate_files_manual() -> List[Dict]:
    """Manually construct climate file paths."""
    base = "ISIMIP3a/InputData/climate/atmosphere/obsclim/global/daily/historical/20CRv3-ERA5"
    base_url = "https://files.isimip.org"

    # Decade chunks needed for 2018-2021
    decade_chunks = [
        (2011, 2020),  # covers 2018-2020
        (2021, 2021),  # covers 2021
    ]

    files = []
    for var in CONFIG.CLIMATE_VARIABLES:
        for start, end in decade_chunks:
            filename = f"20crv3-era5_obsclim_{var}_global_daily_{start}_{end}.nc"
            path = f"{base}/{filename}"
            url = f"{base_url}/{path}"
            files.append({
                'path': path,
                'url': url,
                'variable': var,
                'filename': filename,
                'type': 'climate'
            })

    return files


def get_water_files_manual() -> List[Dict]:
    """Manually construct water model file paths - CORRECTED."""
    model = CONFIG.WATER_MODEL
    forcing = "20crv3-era5"
    soc = CONFIG.WATER_SOCIAL_SCENARIO  # 1901soc

    base = f"ISIMIP3a/OutputData/water_global/H08/{forcing}/historical"
    base_url = "https://files.isimip.org"

    # Decade chunks for 20crv3-era5 (covers through 2021)
    decade_chunks = [
        (2011, 2020),
        (2021, 2021),
    ]

    files = []
    for var in CONFIG.WATER_VARIABLES:
        for start, end in decade_chunks:
            # CORRECTED filename pattern: h08_20crv3-era5_obsclim_1901soc_default_{var}_global_daily_{start}_{end}.nc
            filename = f"{model}_{forcing}_obsclim_{soc}_default_{var}_global_daily_{start}_{end}.nc"
            path = f"{base}/{filename}"
            url = f"{base_url}/{path}"
            files.append({
                'path': path,
                'url': url,
                'variable': var,
                'filename': filename,
                'type': 'water',
                'forcing': forcing
            })

    return files


def get_remote_file_size(url: str) -> Optional[int]:
    """Get file size from server via HEAD request."""
    try:
        response = requests.head(url, timeout=10, allow_redirects=True)
        if response.status_code == 200:
            return int(response.headers.get('content-length', 0))
    except:
        pass
    return None


def verify_file_exists(url: str) -> bool:
    """Check if file exists on server."""
    try:
        response = requests.head(url, timeout=10, allow_redirects=True)
        return response.status_code == 200
    except:
        return False


def discover_files() -> Dict[str, List[Dict]]:
    """Discover all files to download."""
    logger = logging.getLogger('ISIMIP')

    print("\n" + "=" * 60)
    print("DISCOVERING FILES")
    print("=" * 60)

    # Climate files
    print("\nSearching for climate files (20CRv3-ERA5 input)...")
    climate_files = get_climate_files_manual()

    print(f"Verifying {len(climate_files)} climate file paths...")
    valid_climate = []
    for f in tqdm(climate_files, desc="Checking climate"):
        if verify_file_exists(f['url']):
            # Get remote size for skip comparison
            f['remote_size'] = get_remote_file_size(f['url'])
            valid_climate.append(f)
        else:
            logger.debug(f"Not found: {f['path']}")
        time.sleep(0.2)

    # Water files
    print("\nSearching for H08 water model files (20CRv3-ERA5 forcing)...")
    water_files = get_water_files_manual()

    print(f"Verifying {len(water_files)} water file paths...")
    valid_water = []
    for f in tqdm(water_files, desc="Checking water"):
        if verify_file_exists(f['url']):
            f['remote_size'] = get_remote_file_size(f['url'])
            valid_water.append(f)
        else:
            logger.warning(f"Not found: {f['filename']}")
        time.sleep(0.2)

    print(f"\n✓ Found {len(valid_climate)} climate files")
    print(f"✓ Found {len(valid_water)} water files")

    return {
        'climate': valid_climate,
        'water': valid_water
    }


# =============================================================================
# SKIP LOGIC
# =============================================================================

def should_skip_file(filepath: Path, remote_size: Optional[int]) -> Tuple[bool, str]:
    """
    Check if file should be skipped.

    Returns:
        (should_skip, reason)
    """
    if not CONFIG.SKIP_EXISTING:
        return False, ""

    if not filepath.exists():
        return False, ""

    local_size = filepath.stat().st_size

    # If we don't know remote size, check if file is non-empty
    if remote_size is None:
        if local_size > 0:
            return True, f"exists ({local_size / 1e6:.1f} MB, remote size unknown)"
        return False, ""

    # Compare sizes
    if local_size == remote_size:
        return True, f"complete ({local_size / 1e6:.1f} MB)"

    # Allow small tolerance (some servers report slightly different sizes)
    if remote_size > 0:
        diff_ratio = abs(local_size - remote_size) / remote_size
        if diff_ratio < CONFIG.SIZE_TOLERANCE:
            return True, f"complete (~{local_size / 1e6:.1f} MB)"

    # File exists but incomplete
    if local_size < remote_size:
        return False, f"incomplete ({local_size / 1e6:.1f} / {remote_size / 1e6:.1f} MB)"

    # Local file larger than remote (shouldn't happen, re-download)
    return False, f"size mismatch (local: {local_size}, remote: {remote_size})"


# =============================================================================
# DOWNLOAD FUNCTIONS
# =============================================================================

def download_file(url: str, filepath: Path, resume: bool = True) -> bool:
    """Download file with progress bar and resume support."""
    logger = logging.getLogger('ISIMIP')

    filepath.parent.mkdir(parents=True, exist_ok=True)

    # Check for partial download
    existing_size = 0
    headers = {}
    mode = 'wb'

    if resume and filepath.exists():
        existing_size = filepath.stat().st_size
        headers = {'Range': f'bytes={existing_size}-'}
        mode = 'ab'

    try:
        time.sleep(CONFIG.DELAY_BETWEEN_REQUESTS)

        response = requests.get(url, headers=headers, stream=True, timeout=CONFIG.TIMEOUT)

        if response.status_code == 416:
            # Range Not Satisfiable = file already complete
            logger.info(f"Already complete: {filepath.name}")
            return True

        response.raise_for_status()

        content_length = response.headers.get('content-length')
        total_size = int(content_length) + existing_size if content_length else 0

        with open(filepath, mode) as f:
            with tqdm(total=total_size, initial=existing_size, unit='B',
                     unit_scale=True, desc=filepath.name[:40], leave=True) as pbar:
                for chunk in response.iter_content(chunk_size=CONFIG.CHUNK_SIZE):
                    if chunk:
                        f.write(chunk)
                        pbar.update(len(chunk))

        return True

    except Exception as e:
        logger.error(f"Download error {filepath.name}: {e}")
        return False


def download_with_retry(url: str, filepath: Path) -> bool:
    """Download with exponential backoff retry."""
    logger = logging.getLogger('ISIMIP')

    for attempt in range(CONFIG.MAX_RETRIES):
        if attempt > 0:
            wait = 5 * (2 ** attempt)
            logger.info(f"Retry {attempt}/{CONFIG.MAX_RETRIES} in {wait}s...")
            time.sleep(wait)

        if download_file(url, filepath):
            return True

    return False


# =============================================================================
# MAIN
# =============================================================================

def main():
    print("=" * 70)
    print("ISIMIP 20CRv3-ERA5 Europe Downloader (v3 - Fixed Paths)")
    print("=" * 70)
    print(f"Period: {CONFIG.START_YEAR} - {CONFIG.END_YEAR}")
    print(f"Climate variables: {CONFIG.CLIMATE_VARIABLES}")
    print(f"Water variables: {CONFIG.WATER_VARIABLES} (H08, {CONFIG.WATER_SOCIAL_SCENARIO})")
    print(f"Skip existing files: {CONFIG.SKIP_EXISTING}")
    print("=" * 70)

    # Setup
    download_path = setup_download_path()
    print(f"Download path: {download_path}")

    logger = setup_logging(download_path)
    logger.info("Starting download session")

    # Create subdirs
    climate_path = download_path / "climate"
    water_path = download_path / "water"
    climate_path.mkdir(exist_ok=True)
    water_path.mkdir(exist_ok=True)

    # Discover files
    files = discover_files()

    total = len(files['climate']) + len(files['water'])
    if total == 0:
        print("\n❌ No files found!")
        print("\nPossible issues:")
        print("1. Network connectivity problem")
        print("2. ISIMIP server may be down")
        print("\nYou can manually download from:")
        print("  https://data.isimip.org/search/tree/ISIMIP3a/")
        return

    # Check which files need downloading
    print("\n" + "=" * 60)
    print("CHECKING EXISTING FILES")
    print("=" * 60)

    to_download = {'climate': [], 'water': []}
    skipped = {'climate': [], 'water': []}

    print("\nClimate files:")
    for f in files['climate']:
        filepath = climate_path / f['filename']
        skip, reason = should_skip_file(filepath, f.get('remote_size'))
        if skip:
            print(f"  ⏭️  SKIP: {f['filename']} - {reason}")
            skipped['climate'].append(f)
        else:
            if reason:
                print(f"  📥 DOWNLOAD: {f['filename']} - {reason}")
            else:
                print(f"  📥 DOWNLOAD: {f['filename']}")
            to_download['climate'].append(f)

    print("\nWater files:")
    for f in files['water']:
        filepath = water_path / f['filename']
        skip, reason = should_skip_file(filepath, f.get('remote_size'))
        if skip:
            print(f"  ⏭️  SKIP: {f['filename']} - {reason}")
            skipped['water'].append(f)
        else:
            if reason:
                print(f"  📥 DOWNLOAD: {f['filename']} - {reason}")
            else:
                print(f"  📥 DOWNLOAD: {f['filename']}")
            to_download['water'].append(f)

    # Summary
    total_skip = len(skipped['climate']) + len(skipped['water'])
    total_download = len(to_download['climate']) + len(to_download['water'])

    print(f"\n📊 Summary:")
    print(f"   Files to skip: {total_skip}")
    print(f"   Files to download: {total_download}")

    if total_download == 0:
        print("\n✅ All files already downloaded!")
        print(f"\nFiles location: {download_path}")
        return

    # Estimate size
    est_gb = len(to_download['climate']) * 2.5 + len(to_download['water']) * 0.9
    print(f"\n   Estimated download: ~{est_gb:.1f} GB")

    # Confirm
    print("\n" + "=" * 60)
    response = input("Proceed with download? [y/N]: ").strip().lower()
    if response != 'y':
        print("Cancelled.")
        return

    # Download
    print("\n" + "=" * 60)
    print("DOWNLOADING")
    print("=" * 60)

    success = 0
    failed = 0

    # Climate files
    if to_download['climate']:
        print("\nDownloading climate files...")
        for f in to_download['climate']:
            filepath = climate_path / f['filename']

            if download_with_retry(f['url'], filepath):
                success += 1
            else:
                failed += 1
                logger.error(f"Failed: {f['filename']}")

    # Water files
    if to_download['water']:
        print("\nDownloading water files...")
        for f in to_download['water']:
            filepath = water_path / f['filename']

            if download_with_retry(f['url'], filepath):
                success += 1
            else:
                failed += 1
                logger.error(f"Failed: {f['filename']}")

    # Final Summary
    print("\n" + "=" * 60)
    print("DOWNLOAD COMPLETE")
    print("=" * 60)
    print(f"✓ Downloaded: {success}")
    print(f"⏭️  Skipped: {total_skip}")
    print(f"✗ Failed: {failed}")
    print(f"\nFiles saved to: {download_path}")

    # Next steps
    print("\n📋 Next step: Subset to Europe with xarray")
    print("```python")
    print("import xarray as xr")
    print("ds = xr.open_dataset('filename.nc')")
    print("europe = ds.sel(lat=slice(35, 72), lon=slice(-15, 45))")
    print("europe.to_netcdf('filename_europe.nc')")
    print("```")

    logger.info(f"Done. Downloaded: {success}, Skipped: {total_skip}, Failed: {failed}")


if __name__ == "__main__":
    main()

#!/usr/bin/env python3
"""
ISIMIP Europe Subsetting Script v2
Subsets global NetCDF files to Europe bounding box, merges time periods.
"""

import xarray as xr
from pathlib import Path
from collections import defaultdict
import warnings
warnings.filterwarnings('ignore')

# ============================================================
# CONFIGURATION
# ============================================================

class CONFIG:
    # Input/output paths (Google Drive in Colab)
    INPUT_DIR = Path("/content/drive/MyDrive/ISIMIP_Data/20crv3-era5_europe")
    OUTPUT_DIR = Path("/content/drive/MyDrive/ISIMIP_Data/20crv3-era5_europe/subsetted")

    # Europe bounding box
    LAT_MIN = 35.0
    LAT_MAX = 72.0
    LON_MIN = -15.0
    LON_MAX = 45.0

    # Target time period
    TIME_START = "2018-01-01"
    TIME_END = "2021-12-31"

# ============================================================
# FUNCTIONS
# ============================================================

def get_file_size_mb(filepath: Path) -> float:
    if filepath.exists():
        return filepath.stat().st_size / (1024 * 1024)
    return 0.0

def get_variable_key(filename: str) -> str:
    """
    Extract variable key for grouping files.
    E.g., '20crv3-era5_obsclim_pr_global_daily_2011_2020.nc' -> '20crv3-era5_obsclim_pr'
          'h08_20crv3-era5_obsclim_1901soc_default_dis_global_daily_2011_2020.nc' -> 'h08_20crv3-era5_obsclim_1901soc_default_dis'
    """
    # Remove extension
    name = filename.replace('.nc', '')

    # Remove year range at end (e.g., _2011_2020, _2021_2021)
    parts = name.rsplit('_', 2)
    if len(parts) >= 3 and parts[-2].isdigit() and parts[-1].isdigit():
        name = '_'.join(parts[:-2])

    # Remove 'global_daily' to get the variable key
    name = name.replace('_global_daily', '')

    return name

def generate_output_name(var_key: str) -> str:
    """Generate output filename from variable key."""
    return f"{var_key}_europe_daily_2018_2021.nc"

def subset_spatial(ds, lat_name: str, lon_name: str):
    """Subset to Europe bounding box."""
    lat_vals = ds[lat_name].values
    if lat_vals[0] > lat_vals[-1]:  # Descending
        lat_slice = slice(CONFIG.LAT_MAX, CONFIG.LAT_MIN)
    else:  # Ascending
        lat_slice = slice(CONFIG.LAT_MIN, CONFIG.LAT_MAX)

    return ds.sel(**{
        lat_name: lat_slice,
        lon_name: slice(CONFIG.LON_MIN, CONFIG.LON_MAX)
    })

def subset_temporal(ds):
    """Subset to target time period."""
    if 'time' in ds.dims:
        return ds.sel(time=slice(CONFIG.TIME_START, CONFIG.TIME_END))
    return ds

def process_variable_group(var_key: str, files: list, output_dir: Path) -> dict:
    """Process a group of files for same variable, merge time periods."""

    result = {
        "variable": var_key,
        "input_files": [f.name for f in files],
        "input_size_mb": sum(get_file_size_mb(f) for f in files),
        "output_size_mb": 0.0,
        "success": False,
        "message": ""
    }

    output_name = generate_output_name(var_key)
    output_path = output_dir / output_name

    try:
        print(f"\n  Processing: {var_key}")
        for f in files:
            print(f"    - {f.name} ({get_file_size_mb(f):.0f} MB)")

        datasets = []

        for fpath in sorted(files):
            print(f"    Loading {fpath.name}...", end=" ", flush=True)
            ds = xr.open_dataset(fpath)

            # Get coord names
            lat_name = 'lat' if 'lat' in ds.coords else 'latitude'
            lon_name = 'lon' if 'lon' in ds.coords else 'longitude'

            # Subset spatial
            ds = subset_spatial(ds, lat_name, lon_name)

            # Subset temporal
            ds = subset_temporal(ds)

            if 'time' in ds.dims and len(ds.time) > 0:
                print(f"{len(ds.time)} days")
                datasets.append(ds)
            else:
                print("no data in range, skipping")
                ds.close()

        if not datasets:
            result["message"] = "No data in target time range"
            return result

        # Merge time periods
        print(f"    Merging {len(datasets)} datasets...", end=" ", flush=True)

        if len(datasets) == 1:
            merged = datasets[0]
        else:
            merged = xr.concat(datasets, dim='time')
            merged = merged.sortby('time')

        # Remove duplicates if any
        if 'time' in merged.dims:
            _, unique_idx = np.unique(merged.time.values, return_index=True)
            if len(unique_idx) < len(merged.time):
                merged = merged.isel(time=sorted(unique_idx))

        print(f"total {len(merged.time)} days")

        # Save with compression
        print(f"    Saving: {output_name}...", end=" ", flush=True)
        output_dir.mkdir(parents=True, exist_ok=True)

        encoding = {}
        for var in merged.data_vars:
            encoding[var] = {
                'zlib': True,
                'complevel': 4,
                'dtype': 'float32'
            }

        merged.to_netcdf(output_path, encoding=encoding)

        # Cleanup
        for ds in datasets:
            ds.close()
        merged.close()

        result["output_size_mb"] = get_file_size_mb(output_path)
        result["output_file"] = output_name
        result["success"] = True

        reduction = (1 - result["output_size_mb"] / result["input_size_mb"]) * 100
        print(f"done! {result['output_size_mb']:.0f} MB ({reduction:.0f}% reduction)")

    except Exception as e:
        result["message"] = str(e)
        print(f"ERROR: {e}")
        import traceback
        traceback.print_exc()

    return result

def find_and_group_files(input_dir: Path) -> dict:
    """Find all NetCDF files and group by variable."""

    all_files = []

    # Check subdirectories
    for subdir in ['climate', 'water', '']:
        search_dir = input_dir / subdir if subdir else input_dir
        if search_dir.exists():
            all_files.extend(search_dir.glob("*.nc"))

    # Remove duplicates and exclude subsetted
    all_files = [f for f in set(all_files)
                 if "_europe_" not in f.name
                 and "subsetted" not in str(f)]

    # Group by variable
    groups = defaultdict(list)
    for f in all_files:
        key = get_variable_key(f.name)
        groups[key].append(f)

    return dict(groups)

# ============================================================
# MAIN
# ============================================================

def main():
    import numpy as np
    global np  # Make available to process function

    print("=" * 70)
    print("ISIMIP Europe Subsetting Script v2 (with time merging)")
    print("=" * 70)
    print(f"Bounding box: {CONFIG.LAT_MIN}°N - {CONFIG.LAT_MAX}°N, {CONFIG.LON_MIN}°E - {CONFIG.LON_MAX}°E")
    print(f"Time period: {CONFIG.TIME_START} to {CONFIG.TIME_END}")
    print(f"Input: {CONFIG.INPUT_DIR}")
    print(f"Output: {CONFIG.OUTPUT_DIR}")
    print("=" * 70)

    # Find and group files
    groups = find_and_group_files(CONFIG.INPUT_DIR)

    if not groups:
        print("\n❌ No NetCDF files found!")
        return

    print(f"\nFound {sum(len(v) for v in groups.values())} files in {len(groups)} variable groups:\n")

    total_input_mb = 0
    for key, files in sorted(groups.items()):
        size = sum(get_file_size_mb(f) for f in files)
        total_input_mb += size
        print(f"  {key}:")
        for f in sorted(files):
            print(f"    • {f.name} ({get_file_size_mb(f):.0f} MB)")

    print(f"\nTotal input size: {total_input_mb / 1024:.2f} GB")

    # Process each variable group
    print("\n" + "=" * 70)
    print("PROCESSING (subset + merge)")
    print("=" * 70)

    results = []
    for var_key, files in sorted(groups.items()):
        result = process_variable_group(var_key, files, CONFIG.OUTPUT_DIR)
        results.append(result)

    # Summary
    print("\n" + "=" * 70)
    print("SUMMARY")
    print("=" * 70)

    successful = [r for r in results if r["success"]]
    failed = [r for r in results if not r["success"]]

    total_input = sum(r["input_size_mb"] for r in results)
    total_output = sum(r["output_size_mb"] for r in successful)

    print(f"\n✓ Processed: {len(successful)}/{len(results)} variable groups")
    if failed:
        print(f"✗ Failed: {len(failed)}")
        for r in failed:
            print(f"    - {r['variable']}: {r['message']}")

    print(f"\n📊 Size reduction:")
    print(f"   Input:  {total_input / 1024:.2f} GB ({sum(len(r['input_files']) for r in results)} files)")
    print(f"   Output: {total_output / 1024:.2f} GB ({len(successful)} files)")
    print(f"   Saved:  {(total_input - total_output) / 1024:.2f} GB ({(1 - total_output/total_input) * 100:.0f}%)")

    print(f"\n📁 Output files in: {CONFIG.OUTPUT_DIR}")

    if successful:
        print("\nFinal subsetted files:")
        for r in sorted(successful, key=lambda x: x.get('output_file', '')):
            print(f"  • {r.get('output_file', 'unknown')} ({r['output_size_mb']:.0f} MB)")

if __name__ == "__main__":
    main()